### PR TITLE
Added the shuffle parameter to the trainTestSplit function

### PR DESCRIPTION
**Pull request by uttammittal02**

### CODE REVIEW

**Comment by uttammittal02** [comment]
@Ishwarendra kindly review this pr

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Comment by Ishwarendra** [comment]
> @Ishwarendra kindly review this pr

Its better not to keep this parameter. In sklearn lib also irrespective of `shuffle` value, splitting is done randomly.

**Review by harshjohar — CHANGES_REQUESTED** [review]
Aight so we aint doing this right? @Ishwarendra

**Pull request closed without merging**
