### PR TITLE
Added Gaussian Naive Bayes  #21 issue

### PR DESCRIPTION
**Pull request by Sar-thak-3**

### CODE REVIEW

**Review by ken1000minus7 — CHANGES_REQUESTED** [review]
Your commits of the previous pr are still present here, pull the changes from the main branch
Just make sure to create a separate branch whenever working on an algo so this doesn't happen

**Comment by Sar-thak-3** [comment]
Both changes requested are done

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Review by uttammittal02 — APPROVED** [review]
Lgtm

**Pull request merged**
