### PR TITLE
Resolved Issue #64

### PR DESCRIPTION
**Pull request by Modernbeast02**
Implemented addition, subtraction, and multiplication of a matrix with a scaler. Resolved Issue #64

### CODE REVIEW

**Comment by Ishwarendra** [comment]
Hi @Modernbeast02, Do the following changes:
- Update the signature of function in [`matrix.hpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp)  wherever you have introduced new type `G`
- Also update function signature `Matrix<T> operator *=(T num)` to `Matrix<T> operator*=(G num)` in  [`matrix.hpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp) and update its implementation as well in [`matrix.cpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.cpp). Do same update for addition and subtraction operator too.
- Don't implement any function, reuse the already implemented functions. An example is shown below:

<details>

<summary>Right way to overload operator+ are</summary>

```cpp
template <class G, class T>
Matrix<T> operator+(G num, const Matrix<T> &matrix)
{
    Matrix<T> res = matrix;
    res += num;
    return res;
}

template <class T, class G>
Matrix<T> operator+(const Matrix<T> &matrix, G num)
{
    Matrix<T> res = matrix;
    res += num;
    return res;
}
```

</details>

- Check function signatures, don't use `const Type &` everywhere. 
    - For example you have implemented `Matrix<T> operator*(const Matrix<T> &matrix, G num)` but if you see [`matrix.hpp`](https://github.com/PEC-CSS/slowmokit/blob/main/src/slowmokit/ducks/matrix/matrix.hpp) the function signature says `template <class T> Matrix<T> operator*(Matrix<T>, const T &);` Same goes for `operator+` and `operator-` too. 
    - **NOTE that** `Matrix<T>` is passed by value and not by reference.

<details>

<summary>Code for operator* as shown</summary>

```cpp
template <class T, class G>
Matrix<T> operator*(Matrix<T> matrix, const G &num)
{
    matrix *= num;
    return matrix;
}
```

</details>

**Review by Ishwarendra — APPROVED** [review]
Lgtm! Nice job 💖

**Review by harshjohar — APPROVED** [review]
Lgtm

**Review by ken1000minus7 — APPROVED** [review]
Lgtm

**Review by uttammittal02 — CHANGES_REQUESTED** [review]
Resolve all the conflicts once

**Pull request closed without merging**
